### ISSUE TITLE
manifest.jsonのicon URLが存在しないURLになっている

### ISSUE THREAD

**Issue by Ishigami100** [jphacks/tk_2407#62]
frontend/public/manifest.jsonに記載のあるicon URLは現在存在していない画像のURLになっています。PWAとして正しく起動させるためには、ここに存在する画像のURLを指定する必要があります。

そのため、アイコン画像を用意し、その画像を下記のFabicon generatorに通して、画像サイズを一通り揃えたものをpublicに置き、そこにURLの指定を行う。
https://realfavicongenerator.net/

**Comment by Shion1305** [comment]
#71 で解決
